---
- name: 
  hosts: localhost
  gather_facts: false
  tasks:
  - name: print welcome message
    debug: 
      msg: Welcome to Ansible Playbook to Create or Delete S3 Bucket

  - name: Include Variable Files
    include_vars:
      dir: vars

  - name: Create S3 Bucket
    s3_bucket:
      name: "{{ bucket_name }}"
      state: "{{ state }}"
      force: yes
